services:
  - type: web
    name: face-recognition-system
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
